#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 13:07:02 2023

@author: carolin
"""

import pandas as pd
import datetime as dt

def main():
    """
        input:
            1 dataset containing data of all clients per year, generated by split_csv_year.py
        procedure:
            split dataset to contain data of 1 month only
        output:
            1 dataset containing data of all clients per month
    """
    l_year = ["2011", "2012", "2013", "2014"]
    data_path = "../consumption_data/"
    
    # get csv file per year
    for year in l_year: 
        
        filename = year + "_consumption.csv"
        df = pd.read_csv((data_path + filename), sep = ",", index_col = False)
        print("Year: ", year, " size: ", len(df))
        
        # extract data per month for each year
        for x in range(1,13):
            month = "-" + "%02d" % x + "-"
            
            df_split = df[df["date"].str.contains(year + month)]
            print("Month: ", month, " size: ", len(df_split))
            
            month_file = "monthlyConsumption/" + year + month + "eletricity_consumption.csv"
            df_split.to_csv((data_path + month_file), sep = ",", index = False)
        
        # 2015 has only January, stored in 2014 file    
        if year == "2014":
            year = "2015"
            month = "-01-"
            df_split = df[df["date"].str.contains(year + month)]
            print("Month: ", month, " size: ", len(df_split))
            
            month_file = "monthlyConsumption/" + year + month + "eletricity_consumption.csv"
            df_split.to_csv((data_path + month_file), sep = ",", index = False)
        
    
if __name__ == "__main__":
    main()